# Generated by Django 2.0.4 on 2018-04-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('stadium', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NS', 'Not started yet'), ('FT', 'Playing First Time'), ('HT', 'Half Time'), ('ST', 'Playing Second Time'), ('FN', 'Finished')], default='NS', max_length=20)),
                ('team1_score', models.PositiveIntegerField(null=True)),
                ('team2_score', models.PositiveIntegerField(null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionStage')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='teams.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=30)),
                ('minute', models.PositiveIntegerField()),
                ('extra_minute', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player')),
            ],
        ),
    ]
