# Generated by Django 2.0.4 on 2018-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
