# Generated by Django 2.0.4 on 2018-04-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20180416_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='matches.Match'),
        ),
    ]
