# Generated by Django 2.0.4 on 2018-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20180418_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
