# Generated by Django 2.0.4 on 2018-04-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20180418_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='description2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
