# Generated by Django 2.0.4 on 2018-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_matchstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='courner_kicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='dangerous_attacks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='fouls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='free_kicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='passes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='passes_accuracy',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='shots_accuracy',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='shots_ongoal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='shots_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='substitutions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='possession',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
