# Generated by Django 2.0.4 on 2018-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20180527_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='red_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
