# Generated by Django 2.0.4 on 2018-05-30 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_matchstats_red_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_lineup',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=24),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_lineup',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=24),
        ),
    ]
