# Generated by Django 2.0.4 on 2018-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_auto_20180530_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
    ]
