# Generated by Django 2.0.4 on 2018-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_auto_20180531_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_penalty_definition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_penalties_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_penalties_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
