# Generated by Django 2.0.4 on 2018-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_auto_20180602_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
