# Generated by Django 2.0.4 on 2018-06-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_matchevent_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('NS', 'Not started yet'), ('FT', 'Playing First Time'), ('HT', 'Half Time'), ('ST', 'Playing Second Time'), ('ET', 'Playing Extra Time'), ('PN', 'Playing Penalties Definition'), ('FN', 'Finished')], default='NS', max_length=20),
        ),
    ]
