# Generated by Django 2.0.4 on 2018-05-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20180502_2244'),
        ('teams', '0003_auto_20180423_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition'),
        ),
    ]
