# Generated by Django 2.0.4 on 2018-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
