# Generated by Django 2.0.4 on 2018-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_notifications', '0002_auto_20180517_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='notifications_on',
            field=models.BooleanField(default=True),
        ),
    ]
