# Generated by Django 2.0.4 on 2018-04-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('played', models.PositiveIntegerField()),
                ('won', models.PositiveIntegerField()),
                ('drawn', models.PositiveIntegerField()),
                ('lost', models.PositiveIntegerField()),
                ('goal_difference', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionStage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('stage', 'team'), ('stage', 'position')},
        ),
    ]
