# Generated by Django 2.0.4 on 2018-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20180426_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionstage',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='standing',
            name='sub_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
