# Generated by Django 2.0.4 on 2018-04-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180423_2122'),
        ('competitions', '0003_auto_20180426_1430'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('team', 'stage', 'sub_group', 'position'), ('team', 'stage')},
        ),
    ]
