# Generated by Django 2.0.4 on 2018-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20180426_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
