# Generated by Django 2.0.4 on 2018-05-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180423_2122'),
        ('competitions', '0005_standing_is_playing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('team', 'stage', 'sub_group'), ('sub_group', 'position')},
        ),
    ]
