# Generated by Django 2.0.4 on 2018-06-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_competition'),
        ('competitions', '0007_auto_20180609_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('team', 'stage', 'sub_group')},
        ),
    ]
