# Generated by Django 2.0.4 on 2018-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20180614_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
