# Generated by Django 2.0.4 on 2018-06-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20180626_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.CharField(blank=True, default='-', max_length=3),
        ),
    ]
